# Generated by Django 4.0 on 2021-12-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_workout_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excercise',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
