# Generated by Django 4.0 on 2021-12-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_excercise_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='indir.png', null=True, upload_to=''),
        ),
    ]
