# Generated by Django 3.2.10 on 2022-04-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_excercise_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excercise',
            name='video',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
