# Generated by Django 3.2.10 on 2022-04-12 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_excercise_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='excercise',
            name='video_requests',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='excercise',
            name='video',
            field=models.FileField(null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
