# Generated by Django 3.2.10 on 2022-02-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bmi',
            field=models.IntegerField(null=True),
        ),
    ]
