# Generated by Django 3.2.10 on 2022-02-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_profile_bmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateTimeField(null=True),
        ),
    ]
