# Generated by Django 3.2.10 on 2022-02-24 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_profile_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthday',
        ),
    ]
