# Generated by Django 3.2.10 on 2022-02-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_profile_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
