# Generated by Django 3.2.10 on 2022-02-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='user_bmi',
            field=models.IntegerField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='user_height',
            field=models.IntegerField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='user_weight',
            field=models.IntegerField(max_length=3, null=True),
        ),
    ]
